In [1]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
nelgiriyewithana_global_youtube_statistics_2023_path = kagglehub.dataset_download('nelgiriyewithana/global-youtube-statistics-2023')

print('Data source import complete.')
print(f"The dataset data was downloaded to: {nelgiriyewithana_global_youtube_statistics_2023_path}")

Data source import complete.
The dataset data was downloaded to: /kaggle/input/global-youtube-statistics-2023

In [2]:
import numpy as np
import pandas as pd
from datetime import datetime

In [3]:
import os
for dirname, _, filenames in os.walk('/kaggle/input/global-youtube-statistics-2023'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/global-youtube-statistics-2023/Global YouTube Statistics.csv

In [5]:
data_path = '/kaggle/input/global-youtube-statistics-2023/Global YouTube Statistics.csv'

try:
    df = pd.read_csv(data_path, encoding='latin-1')
    print("Arquivo lido com sucesso usando 'latin-1'")
except UnicodeDecodeError as e:
    print(f"Erro ao ler com 'latin-1': {e}")

df.head()

Arquivo lido com sucesso usando 'latin-1'

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country,Abbreviation,channel_type,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
0,1,T-Series,245000000,2.280000e+11,Music,T-Series,20082,India,IN,Music,...,2000000.0,2006.0,Mar,13.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
1,2,YouTube Movies,170000000,0.000000e+00,Film & Animation,youtubemovies,1,United States,US,Games,...,NaN,2006.0,Mar,5.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
2,3,MrBeast,166000000,2.836884e+10,Entertainment,MrBeast,741,United States,US,Entertainment,...,8000000.0,2012.0,Feb,20.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
3,4,Cocomelon - Nursery Rhymes,162000000,1.640000e+11,Education,Cocomelon - Nursery Rhymes,966,United States,US,Education,...,1000000.0,2006.0,Sep,1.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
4,5,SET India,159000000,1.480000e+11,Shows,SET India,116536,India,IN,Entertainment,...,1000000.0,2006.0,Sep,20.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880

In [6]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.15.2)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.11.3)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.0.2)
Collecting htmlmin==0.1.12 (from ydata-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling)
  Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.4.2)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.4)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.60.0)
Collecting PyWavelets (from imagehash==4.3.1->ydata-profiling)
  Downloading pywavelets-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (11.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (2.33.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.4.2)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.29-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 9.3 MB/s eta 0:00:00
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 22.0 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (687 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 35.4 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.4 MB/s eta 0:00:00
Downloading puremagic-1.29-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.2 MB/s eta 0:00:00
Downloading pywavelets-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 97.3 MB/s eta 0:00:00
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=2dcb7388d5a8aa097db547d3d2f29c73419698ae3445ff9f839693362ae55765
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: puremagic, htmlmin, PyWavelets, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed PyWavelets-1.8.0 dacite-1.9.2 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.12 phik-0.12.4 puremagic-1.29 visions-0.8.1 ydata-profiling-4.16.1

In [7]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df, title = "Profiling Report")
profile.to_file("your_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/28 [00:00<?, ?it/s]
 21%|██▏       | 6/28 [00:00<00:00, 40.84it/s]
 39%|███▉      | 11/28 [00:00<00:00, 43.27it/s]
100%|██████████| 28/28 [00:00<00:00, 62.85it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
# Checking for duplicate data
df.duplicated().sum()

np.int64(0)

In [9]:
# Checking for duplicate data
df.Youtuber.duplicated().sum()

np.int64(0)

# Dealing with missing values

In [10]:
pd.set_option('display.max_columns', None)
df

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country,Abbreviation,channel_type,video_views_rank,country_rank,channel_type_rank,video_views_for_the_last_30_days,lowest_monthly_earnings,highest_monthly_earnings,lowest_yearly_earnings,highest_yearly_earnings,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
0,1,T-Series,245000000,2.280000e+11,Music,T-Series,20082,India,IN,Music,1.0,1.0,1.0,2.258000e+09,564600.0,9000000.00,6800000.00,1.084000e+08,2000000.0,2006.0,Mar,13.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
1,2,YouTube Movies,170000000,0.000000e+00,Film & Animation,youtubemovies,1,United States,US,Games,4055159.0,7670.0,7423.0,1.200000e+01,0.0,0.05,0.04,5.800000e-01,NaN,2006.0,Mar,5.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
2,3,MrBeast,166000000,2.836884e+10,Entertainment,MrBeast,741,United States,US,Entertainment,48.0,1.0,1.0,1.348000e+09,337000.0,5400000.00,4000000.00,6.470000e+07,8000000.0,2012.0,Feb,20.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
3,4,Cocomelon - Nursery Rhymes,162000000,1.640000e+11,Education,Cocomelon - Nursery Rhymes,966,United States,US,Education,2.0,2.0,1.0,1.975000e+09,493800.0,7900000.00,5900000.00,9.480000e+07,1000000.0,2006.0,Sep,1.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
4,5,SET India,159000000,1.480000e+11,Shows,SET India,116536,India,IN,Entertainment,3.0,2.0,2.0,1.824000e+09,455900.0,7300000.00,5500000.00,8.750000e+07,1000000.0,2006.0,Sep,20.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,991,Natan por Aï¿,12300000,9.029610e+09,Sports,Natan por Aï¿,1200,Brazil,BR,Entertainment,525.0,55.0,172.0,5.525130e+08,138100.0,2200000.00,1700000.00,2.650000e+07,700000.0,2017.0,Feb,12.0,51.3,2.125594e+08,12.08,183241641.0,-14.235004,-51.925280
991,992,Free Fire India Official,12300000,1.674410e+09,People & Blogs,Free Fire India Official,1500,India,IN,Games,6141.0,125.0,69.0,6.473500e+07,16200.0,258900.00,194200.00,3.100000e+06,300000.0,2018.0,Sep,14.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
992,993,Panda,12300000,2.214684e+09,NaN,HybridPanda,2452,United Kingdom,GB,Games,129005.0,867.0,1202.0,6.703500e+04,17.0,268.00,201.00,3.200000e+03,1000.0,2006.0,Sep,11.0,60.0,6.683440e+07,3.85,55908316.0,55.378051,-3.435973
993,994,RobTopGames,12300000,3.741235e+08,Gaming,RobTopGames,39,Sweden,SE,Games,35112.0,4.0,69.0,3.871000e+06,968.0,15500.00,11600.00,1.858000e+05,100000.0,2012.0,May,9.0,67.0,1.028545e+07,6.48,9021165.0,60.128161,18.643501
994,995,Make Joke Of,12300000,2.129774e+09,Comedy,Make Joke Of,62,India,IN,Comedy,4568.0,125.0,44.0,2.400000e+07,6000.0,96000.00,72000.00,1.200000e+06,100000.0,2017.0,Aug,1.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880

## Category and Channel Type

In [11]:
df.category.isnull().sum()

np.int64(46)

This represents 4.6% of the total.

In [12]:
df.channel_type.isnull().sum()

np.int64(30)

This represents 3% of the total.

To fill in the missing values ​​in the category and channel_type columns, we will use the information present in one column to fill in the other, and if both are missing, fill in with ***Unknown***.

In [13]:
def fill_if_missing(row):
    if pd.isna(row['category']) and pd.isna(row['channel_type']):
        return "Unknown", "Unknown"
    elif pd.isna(row['category']):
        return row['channel_type'], row['channel_type']
    elif pd.isna(row['channel_type']):
        return row['category'], row['category']
    else:
        return row['category'], row['channel_type'] # If both have value, we keep the original values

In [14]:
# Criar uma máscara booleana para identificar linhas com valores faltantes em 'category' ou 'channel_type'
missing_mask = df['category'].isnull() | df['channel_type'].isnull()

In [15]:
# Aplicar a função apenas nas linhas onde a máscara é True
df.loc[missing_mask, ['category', 'channel_type']] = df.loc[missing_mask].apply(
    lambda row: pd.Series(fill_if_missing(row), index=['category', 'channel_type']), axis=1
)

# Você também pode verificar se ainda há valores nulos nessas colunas
print("Number of null values ​​in column 'category':", df['category'].isnull().sum())
print("Number of null values ​​in column 'channel_type':", df['channel_type'].isnull().sum())

Number of null values ​​in column 'category': 0
Number of null values ​​in column 'channel_type': 0

In [16]:
print(df[['category', 'channel_type']].head())

           category   channel_type
0             Music          Music
1  Film & Animation          Games
2     Entertainment  Entertainment
3         Education      Education
4             Shows  Entertainment

## Country

In [17]:
df.Country.isnull().sum()

np.int64(122)

This represents 12.3% of the total. It will be filled with ***Unknown***.

In [18]:
df.Country.fillna("Unknown", inplace = True)

<ipython-input-18-1cd4d23a0de6>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Country.fillna("Unknown", inplace = True)

In [19]:
df.Country.isnull().sum()

np.int64(0)

## Abbreviation

In [20]:
df.Abbreviation.isnull().sum()

np.int64(122)

This represents 12.3% of the total. It will be filled with ***Unknown***.

In [21]:
df.Abbreviation.fillna("Unknown", inplace = True)

<ipython-input-21-cd84d42269a6>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Abbreviation.fillna("Unknown", inplace = True)

In [22]:
df.Abbreviation.isnull().sum()

np.int64(0)

## Video Views Rank

In [23]:
df.video_views_rank.isnull().sum()

np.int64(1)

This represents 0.1% of the total. It will be filled with the ***median***.

In [24]:
df.video_views_rank.median()

915.5

In [25]:
df.video_views_rank.fillna(915, inplace = True)

<ipython-input-25-30fd1efacbd7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.video_views_rank.fillna(915, inplace = True)

In [26]:
df.video_views_rank.isnull().sum()

np.int64(0)

## Country Rank

In [27]:
df.country_rank.isnull().sum()

np.int64(116)

This represents 11.7% of the total. It will be filled with ***0***.

In [28]:
df.country_rank.fillna(0, inplace = True)

<ipython-input-28-4e35a0b24a02>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.country_rank.fillna(0, inplace = True)

In [29]:
df.country_rank.isnull().sum()

np.int64(0)

## Channel Type Rank

In [30]:
df.channel_type_rank.isnull().sum()

np.int64(33)

This represents 3.3% of the total. It will be filled with ***0***.

In [31]:
df.channel_type_rank.fillna(0, inplace = True)

<ipython-input-31-1ccdebee2aea>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.channel_type_rank.fillna(0, inplace = True)

In [32]:
df.channel_type_rank.isnull().sum()

np.int64(0)

## Video Views for the Last 30 Days

In [33]:
df.video_views_for_the_last_30_days.isnull().sum()

np.int64(56)

This represents 5.6% of the total. It will be filled with the ***median***.

In [34]:
df.video_views_for_the_last_30_days.median()

64085000.0

In [35]:
df.video_views_for_the_last_30_days.fillna(64085000.0, inplace = True)

<ipython-input-35-96d7c6f3108e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.video_views_for_the_last_30_days.fillna(64085000.0, inplace = True)

In [36]:
df.video_views_for_the_last_30_days.isnull().sum()

np.int64(0)

## Subscribers for the Last 30 Days

In [37]:
df.subscribers_for_last_30_days.isnull().sum()

np.int64(337)

This represents 33.9% of the total. It will be filled with the ***median***.

In [38]:
df.subscribers_for_last_30_days.median()

200000.0

In [39]:
df.subscribers_for_last_30_days.fillna(200000.0, inplace = True)

<ipython-input-39-a53952284a47>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.subscribers_for_last_30_days.fillna(200000.0, inplace = True)

In [40]:
df.subscribers_for_last_30_days.isnull().sum()

np.int64(0)

## Gross Tertiary Education Enrollment (%)

In [41]:
df["Gross tertiary education enrollment (%)"].isnull().sum()

np.int64(123)

This represents 12.4% of the total. It will be filled with the ***mean***.

In [42]:
df["Gross tertiary education enrollment (%)"].mean()

np.float64(63.62775229357799)

In [43]:
df["Gross tertiary education enrollment (%)"].fillna(63.6, inplace = True)

<ipython-input-43-93b6526097f9>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gross tertiary education enrollment (%)"].fillna(63.6, inplace = True)

In [44]:
df["Gross tertiary education enrollment (%)"].isnull().sum()

np.int64(0)

## Population

In [45]:
df.Population.isnull().sum()

np.int64(123)

This represents 12.4% of the total. It will be filled with the ***median***.

In [46]:
df.Population.median()

328239523.0

In [47]:
df.Population.fillna(328239523.0, inplace = True)

<ipython-input-47-7fff6523f30c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Population.fillna(328239523.0, inplace = True)

In [48]:
df.Population.isnull().sum()

np.int64(0)

## Unemployment Rate

In [49]:
df["Unemployment rate"].isnull().sum()

np.int64(123)

This represents 12.4% of the total. It will be filled with the ***mean***.

In [50]:
df["Unemployment rate"].mean()

np.float64(9.27927752293578)

In [51]:
df["Unemployment rate"].fillna(9.28, inplace = True)

<ipython-input-51-428c74b6ffba>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Unemployment rate"].fillna(9.28, inplace = True)

In [52]:
df["Unemployment rate"].isnull().sum()

np.int64(0)

## Urban Population

In [53]:
df.Urban_population.isnull().sum()

np.int64(123)

This represents 12.4% of the total. It will be filled with the ***median***.

In [54]:
df.Urban_population.median()

270663028.0

In [55]:
df.Urban_population.fillna(270663028.0, inplace = True)

<ipython-input-55-760cc80c0ed6>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Urban_population.fillna(270663028.0, inplace = True)

In [56]:
df.Urban_population.isnull().sum()

np.int64(0)

## Latitude and Longitude

In [57]:
df.Latitude.isnull().sum()

np.int64(123)

In [58]:
df.Longitude.isnull().sum()

np.int64(123)

This represents 12.4% of the total.

In [59]:
# Looking for if where Latitude is null, Longitude is also null and vice versa
latitude_isnull = df.Latitude.isnull()
longitude_isnull = df.Longitude.isnull()

df[latitude_isnull & longitude_isnull]

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country,Abbreviation,channel_type,video_views_rank,country_rank,channel_type_rank,video_views_for_the_last_30_days,lowest_monthly_earnings,highest_monthly_earnings,lowest_yearly_earnings,highest_yearly_earnings,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
5,6,Music,119000000,0.000000e+00,Music,Music,0,Unknown,Unknown,Music,4057944.0,0.0,0.0,64085000.0,0.00,0.00,0.00,0.00,200000.0,2013.0,Sep,24.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
12,13,Gaming,93600000,0.000000e+00,Games,Gaming,0,Unknown,Unknown,Games,4057944.0,0.0,1.0,64085000.0,0.00,0.00,0.00,0.00,200000.0,2013.0,Dec,15.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
14,15,Goldmines,86900000,2.411823e+10,Film & Animation,goldmines,1,Unknown,Unknown,Music,4056562.0,0.0,5663.0,18.0,0.00,0.07,0.05,0.86,200000.0,2006.0,Aug,15.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
38,39,LooLoo Kids - Nursery Rhymes and Children's Songs,54000000,3.231243e+10,Music,LooLoo Kids - Nursery Rhymes and Children's ï¿½,11,Unknown,Unknown,Music,3800129.0,0.0,0.0,159.0,0.04,0.64,0.48,8.00,200000.0,2016.0,Nov,29.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
48,49,Badabun,46800000,1.939805e+10,Entertainment,badabun,1,Unknown,Unknown,Music,4047729.0,0.0,5525.0,440.0,0.11,2.00,1.00,21.00,75.0,2007.0,Jul,21.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,959,Troom Troom PT,12500000,4.384178e+09,Howto & Style,Troom Troom PT,2738,Unknown,Unknown,Howto,1667.0,0.0,37.0,13501000.0,3400.00,54000.00,40500.00,648100.00,200000.0,2015.0,Apr,19.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
967,968,Troom Troom Indonesia,12500000,5.379684e+09,People & Blogs,TROOM TROOM INDONESIA,8,Unknown,Unknown,People,4057418.0,0.0,7712.0,1.0,0.00,0.00,0.00,0.05,200000.0,2020.0,Jul,29.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
972,973,Hero Movies 2023,12400000,1.689091e+09,People & Blogs,Hero Movies 2023,689,Unknown,Unknown,People,6116.0,0.0,63.0,21837000.0,5500.00,87300.00,65500.00,1000000.00,200000.0,2017.0,Feb,22.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
985,986,TKOR,12400000,3.392023e+09,Education,TKoR,0,Unknown,Unknown,People,4057944.0,0.0,7741.0,64085000.0,0.00,0.00,0.00,0.00,200000.0,2006.0,Aug,16.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
986,987,ANNA KOVA,12400000,1.395959e+10,People & Blogs,annakova,1,Unknown,Unknown,Film,4049634.0,0.0,5307.0,2.0,0.00,0.01,0.01,0.10,200000.0,2006.0,Jun,18.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN

In [60]:
# Looking for if all null records of Latitude (and Longitude) have the country.
latitude_isnull = df.Latitude.isnull()
country_notnull = df.Country.notnull()

df[latitude_isnull & country_notnull]

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country,Abbreviation,channel_type,video_views_rank,country_rank,channel_type_rank,video_views_for_the_last_30_days,lowest_monthly_earnings,highest_monthly_earnings,lowest_yearly_earnings,highest_yearly_earnings,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
5,6,Music,119000000,0.000000e+00,Music,Music,0,Unknown,Unknown,Music,4057944.0,0.0,0.0,64085000.0,0.00,0.00,0.00,0.00,200000.0,2013.0,Sep,24.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
12,13,Gaming,93600000,0.000000e+00,Games,Gaming,0,Unknown,Unknown,Games,4057944.0,0.0,1.0,64085000.0,0.00,0.00,0.00,0.00,200000.0,2013.0,Dec,15.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
14,15,Goldmines,86900000,2.411823e+10,Film & Animation,goldmines,1,Unknown,Unknown,Music,4056562.0,0.0,5663.0,18.0,0.00,0.07,0.05,0.86,200000.0,2006.0,Aug,15.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
38,39,LooLoo Kids - Nursery Rhymes and Children's Songs,54000000,3.231243e+10,Music,LooLoo Kids - Nursery Rhymes and Children's ï¿½,11,Unknown,Unknown,Music,3800129.0,0.0,0.0,159.0,0.04,0.64,0.48,8.00,200000.0,2016.0,Nov,29.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
48,49,Badabun,46800000,1.939805e+10,Entertainment,badabun,1,Unknown,Unknown,Music,4047729.0,0.0,5525.0,440.0,0.11,2.00,1.00,21.00,75.0,2007.0,Jul,21.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,959,Troom Troom PT,12500000,4.384178e+09,Howto & Style,Troom Troom PT,2738,Unknown,Unknown,Howto,1667.0,0.0,37.0,13501000.0,3400.00,54000.00,40500.00,648100.00,200000.0,2015.0,Apr,19.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
967,968,Troom Troom Indonesia,12500000,5.379684e+09,People & Blogs,TROOM TROOM INDONESIA,8,Unknown,Unknown,People,4057418.0,0.0,7712.0,1.0,0.00,0.00,0.00,0.05,200000.0,2020.0,Jul,29.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
972,973,Hero Movies 2023,12400000,1.689091e+09,People & Blogs,Hero Movies 2023,689,Unknown,Unknown,People,6116.0,0.0,63.0,21837000.0,5500.00,87300.00,65500.00,1000000.00,200000.0,2017.0,Feb,22.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
985,986,TKOR,12400000,3.392023e+09,Education,TKoR,0,Unknown,Unknown,People,4057944.0,0.0,7741.0,64085000.0,0.00,0.00,0.00,0.00,200000.0,2006.0,Aug,16.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN
986,987,ANNA KOVA,12400000,1.395959e+10,People & Blogs,annakova,1,Unknown,Unknown,Film,4049634.0,0.0,5307.0,2.0,0.00,0.01,0.01,0.10,200000.0,2006.0,Jun,18.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN

In [61]:
df[latitude_isnull & country_notnull].Country.unique()

array(['Unknown', 'Andorra'], dtype=object)

In [62]:
df[latitude_isnull & country_notnull][df[latitude_isnull & country_notnull].Country == 'Andorra']

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country,Abbreviation,channel_type,video_views_rank,country_rank,channel_type_rank,video_views_for_the_last_30_days,lowest_monthly_earnings,highest_monthly_earnings,lowest_yearly_earnings,highest_yearly_earnings,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
663,664,Musas,15100000,2.400038e+09,Howto & Style,Jordi Sala,159,Andorra,AD,People,3889418.0,504.0,7615.0,86.0,0.02,0.34,0.26,4.0,200000.0,2006.0,Mar,12.0,63.6,328239523.0,9.28,270663028.0,NaN,NaN

It will be filled with ***Unknown***.

In [63]:
df.Latitude.fillna("Unknown", inplace = True)
df.Longitude.fillna("Unknown", inplace = True)

<ipython-input-63-6e36486bfb1f>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Latitude.fillna("Unknown", inplace = True)
<ipython-input-63-6e36486bfb1f>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.Latitude.fillna("Unknown", inplace = True)
<ipython-input-63-6e36486bfb1f>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Longitude.fillna("Unknown", inplace = True)
<ipython-input-63-6e36486bfb1f>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.Longitude.fillna("Unknown", inplace = True)

In [64]:
df.Latitude.isnull().sum()

np.int64(0)

In [65]:
df.Longitude.isnull().sum()

np.int64(0)

# Renaming columns

In [66]:
df.columns

Index(['rank', 'Youtuber', 'subscribers', 'video views', 'category', 'Title',
       'uploads', 'Country', 'Abbreviation', 'channel_type',
       'video_views_rank', 'country_rank', 'channel_type_rank',
       'video_views_for_the_last_30_days', 'lowest_monthly_earnings',
       'highest_monthly_earnings', 'lowest_yearly_earnings',
       'highest_yearly_earnings', 'subscribers_for_last_30_days',
       'created_year', 'created_month', 'created_date',
       'Gross tertiary education enrollment (%)', 'Population',
       'Unemployment rate', 'Urban_population', 'Latitude', 'Longitude'],
      dtype='object')

In [67]:
df.rename(columns = {'Youtuber': 'youtuber', 'video views': 'video_views', 'Title': 'title', 'Country': 'country',
                     'Abbreviation': 'abbreviation', 'Gross tertiary education enrollment (%)': 'gross_tertiary_education_enrollment_porcent',
                     'Population': 'population', 'Unemployment rate': 'unemployment_rate', 'Urban_population': 'urban_population',
                     'Latitude': 'latitude', 'Longitude': 'longitude'
                    }, inplace = True)

# Column types

In [68]:
df.dtypes

rank                                             int64
youtuber                                        object
subscribers                                      int64
video_views                                    float64
category                                        object
title                                           object
uploads                                          int64
country                                         object
abbreviation                                    object
channel_type                                    object
video_views_rank                               float64
country_rank                                   float64
channel_type_rank                              float64
video_views_for_the_last_30_days               float64
lowest_monthly_earnings                        float64
highest_monthly_earnings                       float64
lowest_yearly_earnings                         float64
highest_yearly_earnings                        float64
subscribers_for_last_30_days                   float64
created_year                                   float64
created_month                                   object
created_date                                   float64
gross_tertiary_education_enrollment_porcent    float64
population                                     float64
unemployment_rate                              float64
urban_population                               float64
latitude                                        object
longitude                                       object
dtype: object

In [69]:
df.created_date.isnull().sum()

np.int64(5)

Created Year, Created Month and Created Date also have null values, however it was decided that they would remain that way.

# Dealing with date

In [70]:
def format_date(year, abbreviated_month, day):
    months = {
        'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
        'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
    }

    if pd.isna(year) or pd.isna(day) or abbreviated_month not in months:
        return None
    else:
        numeric_month = months[abbreviated_month]
        try:
            return datetime(int(year), numeric_month, int(day)).strftime('%Y-%m-%d')
        except ValueError:
            # Error if date is invalid (eg: April 31st)
            return None

In [71]:
# Converte ano e dia para numérico, transformando não numéricos em NaN
df['created_year'] = pd.to_numeric(df['created_year'], errors = 'coerce')
df['created_date'] = pd.to_numeric(df['created_date'], errors = 'coerce')

In [72]:
df['created_date_formatted'] = df.apply(lambda row: format_date(row['created_year'], row['created_month'], row['created_date']), axis = 1)
print(df[['created_year', 'created_month', 'created_date', 'created_date_formatted']].head())

   created_year created_month  created_date created_date_formatted
0        2006.0           Mar          13.0             2006-03-13
1        2006.0           Mar           5.0             2006-03-05
2        2012.0           Feb          20.0             2012-02-20
3        2006.0           Sep           1.0             2006-09-01
4        2006.0           Sep          20.0             2006-09-20

# Downloading the file

In [73]:
df.head()

,rank,youtuber,subscribers,video_views,category,title,uploads,country,abbreviation,channel_type,video_views_rank,country_rank,channel_type_rank,video_views_for_the_last_30_days,lowest_monthly_earnings,highest_monthly_earnings,lowest_yearly_earnings,highest_yearly_earnings,subscribers_for_last_30_days,created_year,created_month,created_date,gross_tertiary_education_enrollment_porcent,population,unemployment_rate,urban_population,latitude,longitude,created_date_formatted
0,1,T-Series,245000000,2.280000e+11,Music,T-Series,20082,India,IN,Music,1.0,1.0,1.0,2.258000e+09,564600.0,9000000.00,6800000.00,1.084000e+08,2000000.0,2006.0,Mar,13.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.96288,2006-03-13
1,2,YouTube Movies,170000000,0.000000e+00,Film & Animation,youtubemovies,1,United States,US,Games,4055159.0,7670.0,7423.0,1.200000e+01,0.0,0.05,0.04,5.800000e-01,200000.0,2006.0,Mar,5.0,88.2,3.282395e+08,14.70,270663028.0,37.09024,-95.712891,2006-03-05
2,3,MrBeast,166000000,2.836884e+10,Entertainment,MrBeast,741,United States,US,Entertainment,48.0,1.0,1.0,1.348000e+09,337000.0,5400000.00,4000000.00,6.470000e+07,8000000.0,2012.0,Feb,20.0,88.2,3.282395e+08,14.70,270663028.0,37.09024,-95.712891,2012-02-20
3,4,Cocomelon - Nursery Rhymes,162000000,1.640000e+11,Education,Cocomelon - Nursery Rhymes,966,United States,US,Education,2.0,2.0,1.0,1.975000e+09,493800.0,7900000.00,5900000.00,9.480000e+07,1000000.0,2006.0,Sep,1.0,88.2,3.282395e+08,14.70,270663028.0,37.09024,-95.712891,2006-09-01
4,5,SET India,159000000,1.480000e+11,Shows,SET India,116536,India,IN,Entertainment,3.0,2.0,2.0,1.824000e+09,455900.0,7300000.00,5500000.00,8.750000e+07,1000000.0,2006.0,Sep,20.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.96288,2006-09-20

In [74]:
df.to_csv('cleaned_youtube_data.csv', index = False)